# Generated by Django 3.2.3 on 2021-05-19 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_plasma'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasma',
            name='last_donated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plasma',
            name='created_at',
            field=models.DateTimeField(default=False),
        ),
    ]
