# Generated by Django 3.2.3 on 2021-05-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210519_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasma',
            name='last_donated_on',
            field=models.DateTimeField(),
        ),
    ]
