# Generated by Django 3.2.3 on 2021-05-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210517_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='city',
            new_name='taluka',
        ),
    ]
