# Generated by Django 3.2.3 on 2021-05-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
